version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4545:3045"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]


